install.packages("Rcmdr")
install.packages("Ecdat")
install.packages("xlsx")
install.packages("reshape2")
install.packages("car")
install.packages("xts")
install.packages("quantmod")
install.packages("PerformanceAnalytics")
install.packages("RODBC")
install.packages("fPortfolio")
install.packages("BLCOP")
install.packages("urca")
install.packages("forecast")
install.packages("FinTS")
install.packages("rugarch")
install.packages("PairTrading", repos="http://R-Forge.R-project.org")
